//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentsMVC.OptiizationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OptiizationService.IOptimizationService")]
    public interface IOptimizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOptimizationService/DoSimplex", ReplyAction="http://tempuri.org/IOptimizationService/DoSimplexResponse")]
        double[] DoSimplex(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOptimizationService/DoSimplex", ReplyAction="http://tempuri.org/IOptimizationService/DoSimplexResponse")]
        System.Threading.Tasks.Task<double[]> DoSimplexAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOptimizationService/DoBionic", ReplyAction="http://tempuri.org/IOptimizationService/DoBionicResponse")]
        double[] DoBionic(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOptimizationService/DoBionic", ReplyAction="http://tempuri.org/IOptimizationService/DoBionicResponse")]
        System.Threading.Tasks.Task<double[]> DoBionicAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOptimizationServiceChannel : InvestmentsMVC.OptiizationService.IOptimizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OptimizationServiceClient : System.ServiceModel.ClientBase<InvestmentsMVC.OptiizationService.IOptimizationService>, InvestmentsMVC.OptiizationService.IOptimizationService {
        
        public OptimizationServiceClient() {
        }
        
        public OptimizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OptimizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OptimizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OptimizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double[] DoSimplex(int value) {
            return base.Channel.DoSimplex(value);
        }
        
        public System.Threading.Tasks.Task<double[]> DoSimplexAsync(int value) {
            return base.Channel.DoSimplexAsync(value);
        }
        
        public double[] DoBionic(int value) {
            return base.Channel.DoBionic(value);
        }
        
        public System.Threading.Tasks.Task<double[]> DoBionicAsync(int value) {
            return base.Channel.DoBionicAsync(value);
        }
    }
}
